add support for spin KV
spinframework/spin-js-sdk pull request #122
Opened 2023-02-14 20:40 UTC by karthik2804

2023-02-14 20:51 UTC, dicej approved these changes

2023-02-15 18:14 UTC, radu-matei commented on types/lib/modules/spinSdk.d.ts
> +        open: (name: string) => KvObject;
Do we want to add a function to open the default store as well?

2023-02-15 18:14 UTC, radu-matei commented on types/lib/modules/spinSdk.d.ts
> +    set: (key: string, value: ArrayBuffer) => void;
Do we want to make the signature here a bit more flexible?
I'm thinking about making it easier to work with strings in particular, given that (I assume) a lot of scenarios will want to work with JSON data.

2023-02-15 18:17 UTC, karthik2804 commented on types/lib/modules/spinSdk.d.ts
> +    set: (key: string, value: ArrayBuffer) => void;
We could add support for strings in addition to ArrayBuffers. I will add it.

2023-02-15 18:18 UTC, karthik2804 commented on types/lib/modules/spinSdk.d.ts
> +        open: (name: string) => KvObject;
I am not sure it adds much value when we could open it with `spinSdk.kv.open("default")`

2023-02-15 18:26 UTC, radu-matei commented on types/lib/modules/spinSdk.d.ts
> +    set: (key: string, value: ArrayBuffer) => void;
Just in `set`.
Since the lower level API always returns a byte array, there is no way of knowing when to convert something.

Alternatively, we could consider `getString` and `setString`, but I'm not a huge fan of that..

2023-02-15 18:28 UTC, karthik2804 commented on types/lib/modules/spinSdk.d.ts
> +    set: (key: string, value: ArrayBuffer) => void;
Sounds good to me. I will add that to the `set` method.

2023-02-15 18:55 UTC, karthik2804 commented on types/lib/modules/spinSdk.d.ts
> +    set: (key: string, value: ArrayBuffer) => void;
This has been added.

2023-02-15 19:26 UTC, itowlson commented on types/lib/modules/spinSdk.d.ts
> +        open: (name: string) => KvObject;
It avoids the magic string - the compiler will tell me when (not if: when) I mistype it `defualt`.

2023-02-15 19:30 UTC, itowlson requested changes

2023-02-15 19:30 UTC, itowlson commented on crates/spin-js-engine/src/js_sdk/modules/spinSdk.ts
> +interface KvObject {
This is specifically a KV _store_ - 'object' is unnecessarily open-ended for my taste.

2023-02-15 20:02 UTC, karthik2804 commented on types/lib/modules/spinSdk.d.ts
> +        open: (name: string) => KvObject;
That makes sense. I will ad it.

2023-02-15 20:21 UTC, karthik2804 commented on crates/spin-js-engine/src/js_sdk/modules/spinSdk.ts
> +interface KvObject {
changed it to `KvStore`.

2023-02-15 20:22 UTC, karthik2804 commented on types/lib/modules/spinSdk.d.ts
> +        open: (name: string) => KvObject;
Added it now.

2023-02-15 20:32 UTC, itowlson reviewed
This looks fine functionally but it would be good to define our standard for capitalising acronyms because it looks a bit inconsistent at the moment.

2023-02-15 20:32 UTC, itowlson commented on crates/spin-js-engine/src/js_sdk/modules/spinSdk.ts
> +interface KvStore {
`Kv` but `SDK` - do we have a principle on how we capitalise acronyms?

2023-02-15 20:34 UTC, karthik2804 commented on crates/spin-js-engine/src/js_sdk/modules/spinSdk.ts
> +interface KvStore {
I am happy to adopt any principle we choose on this and make the required changes.

2023-02-15 20:45 UTC, itowlson commented on crates/spin-js-engine/src/js_sdk/modules/spinSdk.ts
> +interface KvStore {
ah good catch we already mix Http and SDK, and it would be a breaking change to change either.  Let's live with it.

2023-02-15 20:45 UTC, itowlson approved these changes

2023-02-15 21:07 UTC, karthik2804 commented on crates/spin-js-engine/src/js_sdk/modules/spinSdk.ts
> +interface KvStore {
The user actually interacts only with `spinSdk` not `SpinSDK` therefore I am not sure it would be a breaking change overall but If we do decide on a standard for this, happy to open a new PR with the required changes.

2023-02-16 00:57 UTC, karthik2804 commented
closing in favour for #125

2023-02-16 00:57 UTC, closed without merging