add support for redis and postgres
spinframework/spin-js-sdk pull request #156
Opened 2023-04-01 04:15 UTC by karthik2804

This PR adds support to both mysql and postgres. 

The examples currently use the plugin and types from `HEAD` until a new release is made.

2023-05-10 19:32 UTC, dicej requested changes

2023-05-10 19:32 UTC, dicej commented on crates/spin-js-engine/src/lib.rs
> +        mysql::{self},
```suggestion
        mysql,
```

2023-05-10 19:32 UTC, dicej commented on crates/spin-js-engine/src/lib.rs
> +        pg::{self},
```suggestion
        pg,
```

2023-05-10 19:32 UTC, dicej commented on crates/spin-js-engine/src/lib.rs
> +        redis,
Could combine this line with the next one, e.g. `redis::{self, RedisResult}`

2023-05-10 19:32 UTC, dicej commented on crates/spin-js-engine/src/lib.rs
> +        }
```suggestion
        } else
```

2023-05-10 19:32 UTC, dicej commented on crates/spin-js-engine/src/lib.rs
> +                        .map(|arg| match arg {
Can we move this `match` statement into its own function so it can be reused by `mysql_query`?

2023-05-10 19:32 UTC, dicej commented on crates/spin-js-engine/src/lib.rs
> +                            mysql::DbValue::Unsupported => context.undefined_value()?,
I'm thinking we should return an error here instead of using `undefined`.

2023-05-10 19:32 UTC, dicej commented on crates/spin-js-engine/src/lib.rs
> +                        .map(|arg| match arg {
As with `mysql_execute`, let's deduplicate the `match` statements here and in `postgres_query`.

2023-05-10 19:32 UTC, dicej commented on crates/spin-js-engine/src/lib.rs
> +                            pg::DbValue::Unsupported => context.undefined_value()?,
As above, I'd like to return an error instead of using `undefined` here.

2023-05-12 14:29 UTC, karthik2804 commented
@dicej implemented the changes in the latest push.

2023-05-12 14:35 UTC, dicej approved these changes

2023-05-12 17:43 UTC, merged